package com.yk.entity;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.userId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.sortId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Integer sortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.labelId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Integer labelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleCover
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String articleCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleTitle
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String articleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.videoUrl
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.viewCount
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.likeCount
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Integer likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.viewStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Boolean viewStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.password
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tips
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String tips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.recommendStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Boolean recommendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.commentStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Boolean commentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.createTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updateTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updateBy
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.deleted
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.articleContent
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String articleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.userId
     *
     * @return the value of article.userId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.userId
     *
     * @param userId the value for article.userId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.sortId
     *
     * @return the value of article.sortId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.sortId
     *
     * @param sortId the value for article.sortId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.labelId
     *
     * @return the value of article.labelId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.labelId
     *
     * @param labelId the value for article.labelId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleCover
     *
     * @return the value of article.articleCover
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getArticleCover() {
        return articleCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleCover
     *
     * @param articleCover the value for article.articleCover
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setArticleCover(String articleCover) {
        this.articleCover = articleCover == null ? null : articleCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleTitle
     *
     * @return the value of article.articleTitle
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleTitle
     *
     * @param articleTitle the value for article.articleTitle
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.videoUrl
     *
     * @return the value of article.videoUrl
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.videoUrl
     *
     * @param videoUrl the value for article.videoUrl
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.viewCount
     *
     * @return the value of article.viewCount
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.viewCount
     *
     * @param viewCount the value for article.viewCount
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.likeCount
     *
     * @return the value of article.likeCount
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.likeCount
     *
     * @param likeCount the value for article.likeCount
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.viewStatus
     *
     * @return the value of article.viewStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Boolean getViewStatus() {
        return viewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.viewStatus
     *
     * @param viewStatus the value for article.viewStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setViewStatus(Boolean viewStatus) {
        this.viewStatus = viewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.password
     *
     * @return the value of article.password
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.password
     *
     * @param password the value for article.password
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tips
     *
     * @return the value of article.tips
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tips
     *
     * @param tips the value for article.tips
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setTips(String tips) {
        this.tips = tips == null ? null : tips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.recommendStatus
     *
     * @return the value of article.recommendStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Boolean getRecommendStatus() {
        return recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.recommendStatus
     *
     * @param recommendStatus the value for article.recommendStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setRecommendStatus(Boolean recommendStatus) {
        this.recommendStatus = recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.commentStatus
     *
     * @return the value of article.commentStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Boolean getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.commentStatus
     *
     * @param commentStatus the value for article.commentStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setCommentStatus(Boolean commentStatus) {
        this.commentStatus = commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.createTime
     *
     * @return the value of article.createTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.createTime
     *
     * @param createTime the value for article.createTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updateTime
     *
     * @return the value of article.updateTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.updateTime
     *
     * @param updateTime the value for article.updateTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updateBy
     *
     * @return the value of article.updateBy
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.updateBy
     *
     * @param updateBy the value for article.updateBy
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.deleted
     *
     * @return the value of article.deleted
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.deleted
     *
     * @param deleted the value for article.deleted
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.articleContent
     *
     * @return the value of article.articleContent
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.articleContent
     *
     * @param articleContent the value for article.articleContent
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }
}