package com.yk.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Boolean userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.openId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.admire
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String admire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.introduction
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userType
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Byte userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updateTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updateBy
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.deleted
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.subscribe
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    private String subscribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userStatus
     *
     * @return the value of user.userStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Boolean getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userStatus
     *
     * @param userStatus the value for user.userStatus
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setUserStatus(Boolean userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.openId
     *
     * @return the value of user.openId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.openId
     *
     * @param openId the value for user.openId
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.admire
     *
     * @return the value of user.admire
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getAdmire() {
        return admire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.admire
     *
     * @param admire the value for user.admire
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setAdmire(String admire) {
        this.admire = admire == null ? null : admire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.introduction
     *
     * @return the value of user.introduction
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.introduction
     *
     * @param introduction the value for user.introduction
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userType
     *
     * @return the value of user.userType
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userType
     *
     * @param userType the value for user.userType
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createTime
     *
     * @return the value of user.createTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createTime
     *
     * @param createTime the value for user.createTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.updateTime
     *
     * @return the value of user.updateTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.updateTime
     *
     * @param updateTime the value for user.updateTime
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.updateBy
     *
     * @return the value of user.updateBy
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.updateBy
     *
     * @param updateBy the value for user.updateBy
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.deleted
     *
     * @return the value of user.deleted
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.deleted
     *
     * @param deleted the value for user.deleted
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.subscribe
     *
     * @return the value of user.subscribe
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public String getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.subscribe
     *
     * @param subscribe the value for user.subscribe
     *
     * @mbggenerated Tue Apr 02 23:34:13 CST 2024
     */
    public void setSubscribe(String subscribe) {
        this.subscribe = subscribe == null ? null : subscribe.trim();
    }
}